name: CI/CD for Calci

on:
  push:
    branches:
      - main

env:
  IMAGE_REPO: prajwalbk1999/prajwalbk1999
  DEPLOYMENT_NAME: calci-deployment
  CONTAINER_NAME: calci
  NAMESPACE: calci
  CLUSTER_NAME: eks-dev-cluster

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:    ${{ secrets.AWS_REGION }}

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig \
            --name ${{ env.CLUSTER_NAME }} \
            --region ${{ secrets.AWS_REGION }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_REPO }}:calci-${{ github.sha }}

      - name: Ensure Namespace exists
        run: |
          if ! kubectl get namespace ${{ env.NAMESPACE }}; then
            kubectl apply -f namespace.yaml
          fi

      - name: Deploy Service
        run: kubectl apply -f service.yaml -n ${{ env.NAMESPACE }}

      - name: Rollout new image
        run: |
          kubectl set image \
            deployment/${{ env.DEPLOYMENT_NAME }} \
            ${{ env.CONTAINER_NAME }}=${{ env.IMAGE_REPO }}:calci-${{ github.sha }} \
            -n ${{ env.NAMESPACE }}
